#!/usr/bin/python3
#+
# DBussy example -- ask the bigben server for the current “time”.
#
# Copyright 2017 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import dbussy as dbus
from dbussy import \
    DBUS

my_bus_name = "com.example.bigben"
my_path_name = "/com/example/bigben"
my_iface_name = "com.example.bigben"

#+
# Mainline
#-

conn = dbus.Connection.bus_get(DBUS.BUS_SESSION, private = False)
message = dbus.Message.new_method_call \
  (
    destination = my_bus_name,
    path = my_path_name,
    iface = my_iface_name,
    method = "whats_the_time"
  )
reply = conn.send_with_reply_and_block(message)
sys.stdout.write(reply.expect_return_objects("s")[0] + "\n")
