#!/usr/bin/python3
#+
# DBussy example -- wait until the next chime from the bigben server.
#
# Copyright 2017 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import signal
import dbussy as dbus
from dbussy import \
    DBUS

my_bus_name = "com.example.bigben"
my_path_name = "/com/example/bigben"
my_iface_name = "com.example.bigben"

loop = dbus.get_event_loop()

signal.signal(signal.SIGINT, signal.SIG_DFL) # abort without raising KeyboardInterrupt on CTRL/C

#+
# Mainline
#-

async def mainline() :
    conn = await dbus.Connection.bus_get_async \
      (
        type = DBUS.BUS_SESSION,
        private = False,
        loop = loop
      )
    message = dbus.Message.new_method_call \
      (
        destination = my_bus_name,
        path = my_path_name,
        iface = my_iface_name,
        method = "await_chime"
      )
    reply = await conn.send_await_reply(message)
#end mainline

loop.run_until_complete(mainline())
