#!/usr/bin/python3
#+
# DBussy example -- a listener which reports the chimes from the bigben
# server every “hour”.
#
# Copyright 2017 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import asyncio
import dbussy as dbus
from dbussy import \
    DBUS

my_bus_name = "com.example.bigben"
my_path_name = "/com/example/bigben"
my_iface_name = "com.example.bigben"
chime_signal_name = "chime"

loop = asyncio.get_event_loop()

def handle_message(conn, message, user_data) :
    sys.stdout.write(" ".join(message.objects) + "\n")
    return \
        DBUS.HANDLER_RESULT_HANDLED
#end handle_message

#+
# Mainline
#-

conn = dbus.Connection.bus_get(DBUS.BUS_SESSION, private = False)
conn.attach_asyncio(loop)
conn.bus_add_match \
  (
        "type='%(type)s',interface='%(interface)s',member='%(member)s'"
    %
        {"type" : "signal", "interface" : my_iface_name, "member" : chime_signal_name}
  )
conn.register_fallback \
  (
    path = my_path_name,
    vtable = dbus.ObjectPathVTable
      (
        loop = loop,
        message = handle_message,
      ),
    user_data = None
  )
loop.run_forever()
