#!/usr/bin/python3
#+
# DBussy example -- a listener which reports the chimes from the bigben
# server every “hour”.
#
# This version uses the ravel higher-level API.
#
# Copyright 2017 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import signal
import dbussy
from dbussy import \
    DBUS
import ravel

my_bus_name = "com.example.bigben"
my_path_name = "/com/example/bigben"
my_iface_name = "com.example.bigben"
chime_signal_name = "chime"

loop = dbussy.get_event_loop()

signal.signal(signal.SIGINT, signal.SIG_DFL) # abort without raising KeyboardInterrupt on CTRL/C

@ravel.signal(name = "chime", in_signature = "as", args_keyword = "args")
def chime_received(args) :
    sys.stdout.write(" ".join(args[0]) + "\n")
#end chime_received

#+
# Mainline
#-

bus = ravel.session_bus()
bus.attach_asyncio(loop)
bus.listen_signal \
  (
    path = "/",
    fallback = True,
    interface = my_iface_name,
    name = chime_signal_name,
    func = chime_received
  )
loop.run_forever()
