#!/usr/bin/python3
#+
# DBussy example -- obtain all property values for an interface at an
# object path from a bus peer. Invoke this script as follows:
#
#     get-props session|system «bus_name» «path» «interface»
#
# For example, you can get info about your machine hostname with the
# command
#
#     get-props system org.freedesktop.hostname1 /org/freedesktop/hostname1 \
#         org.freedesktop.hostname1
#
# and you can get info about your current login with the commands
#
#     get-props system org.freedesktop.login1 /org/freedesktop/login1/session/self \
#         org.freedesktop.login1.Session
#     get-props system org.freedesktop.login1 /org/freedesktop/login1/seat/self \
#         org.freedesktop.login1.Seat
#     get-props system org.freedesktop.login1 /org/freedesktop/login1/user/self \
#         org.freedesktop.login1.User
#
# Copyright 2017 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import asyncio
import getopt
import dbussy as dbus
from dbussy import \
    DBUS

#+
# Mainline
#-

loop = asyncio.get_event_loop()

if len(sys.argv) != 5 :
    raise getopt.GetoptError("usage: %s session|system «bus-name» «path» «interface»" % sys.argv[0])
#end if
which_bus, destination, object_path, interface_name = sys.argv[1:]

conn = dbus.Connection.bus_get \
  (
    {"session" : DBUS.BUS_SESSION, "system" : DBUS.BUS_SYSTEM}[which_bus.lower()],
    private = False
  )
conn.attach_asyncio(loop)

request = dbus.Message.new_method_call \
  (
    destination = dbus.valid_bus_name(destination),
    path = dbus.valid_path(object_path),
    iface = DBUS.INTERFACE_PROPERTIES,
    method = "GetAll"
  )
request.append_objects("s", dbus.valid_interface(interface_name))
reply = loop.run_until_complete(conn.send_await_reply(request))
values = reply.expect_return_objects("a{sv}")[0]
for propname in sorted(values.keys()) :
    proptype, propvalue = values[propname]
    sys.stdout.write("%s(%s) = %s\n" % (propname, proptype, repr(propvalue)))
#end for
