#!/usr/bin/python3
#+
# DBussy example -- listen for signals on D-Bus using thread-blocking calls.
#
# Copyright 2017 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import getopt
import dbussy as dbus
from dbussy import \
    DBUS

#+
# Callbacks
#-

def message_filter(connection, message, data) :
    sys.stdout.write("filter got a message, type %s(%d), serial = %d, sig = %s\n" % (message.type_to_string(message.type), message.type, message.serial, repr(message.signature)))
    if message.type == DBUS.MESSAGE_TYPE_METHOD_CALL :
        sys.stdout.write(" destination = %s\n" % repr(message.destination))
    #end if
    if message.type in (DBUS.MESSAGE_TYPE_METHOD_CALL, DBUS.MESSAGE_TYPE_SIGNAL) :
        sys.stdout.write(" path = %s, interface = %s, name = %s\n" % (repr(message.path), repr(message.interface), repr(message.member)))
    #end if
    sys.stdout.write(" contents = %s\n" % repr(message.all_objects))
    return \
        DBUS.HANDLER_RESULT_HANDLED
#end message_filter

#+
# Mainline
#-

if len(sys.argv) != 2 :
    raise getopt.GetoptError("usage: %s session|system" % sys.argv[0])
#end if

conn = dbus.Connection.bus_get({"session" : DBUS.BUS_SESSION, "system" : DBUS.BUS_SYSTEM}[sys.argv[1].lower()], private = False)
conn.add_filter(message_filter, None)
conn.bus_add_match("type='signal'")
while conn.read_write_dispatch() :
    pass
#end while
